import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,step,damage,snapshot,restore,SAVE_KEY} from '../app/living-forest/engine.mjs';
test('shield absorbs one hit and invulnerability rejects simultaneous hits',()=>{const g=createGame();g.player.shield=3;damage(g);damage(g);assert.equal(g.player.shield,2);assert.equal(g.player.lives,3);});
test('checkpoint restores equipment without farming rewards or replenishing lives',()=>{const g=createGame();g.player.weapon=2;g.player.shield=2;g.blocks[0].broken=true;g.coins=5;g.checkpoint=snapshot(g);g.player.shield=0;damage(g);assert.equal(g.player.weapon,2);assert.equal(g.player.shield,2);assert.equal(g.player.lives,2);assert.equal(g.blocks[0].broken,true);g.player.shield=0;g.player.inv=0;damage(g);assert.equal(g.player.lives,1);});
test('invalid save rejected and existing game save has separate key',()=>{assert.notEqual(SAVE_KEY,'woody-forest-adventure');const g=restore({version:1,player:{x:NaN}});assert.equal(g.player.lives,3);});
test('every ascending platform is reachable with normal jump physics',()=>{const base=createGame();for(let i=1;i<base.platforms.length;i++){const a=base.platforms[i-1],b=base.platforms[i];const g=createGame();g.paused=false;g.enemies=[];g.blocks=[];g.boss.hp=100;g.boss.y=-1000;g.player.x=i===1?200:(b.x>a.x?a.x+a.w-45:a.x+12);g.player.y=a.y-g.player.h;g.player.ground=true;const direction=b.x>g.player.x?1:-1;g.keys={jump:true,right:direction>0,left:direction<0};let landed=false;for(let n=0;n<100;n++){const center=g.player.x+16;if(center>b.x+12&&center<b.x+b.w-12)g.keys.right=g.keys.left=false;step(g,1/60);if(g.player.ground&&Math.abs(g.player.y+48-b.y)<1){landed=true;break;}}assert.ok(landed,`platform ${i} reachable`);}});
test('spring provides equipment and checkpoint before boss',()=>{const g=createGame();g.paused=false;g.player.x=1200;g.player.y=492;g.keys.peck=true;step(g,1/60);assert.equal(g.water,true);assert.equal(g.player.weapon,3);assert.equal(g.checkpoint.player.shield,3);});
test('jump release shortens ascent and coyote time permits late jump',()=>{const g=createGame();g.paused=false;g.enemies=[];g.player.ground=false;g.player.coyote=.08;g.keys.jump=true;step(g,1/60);assert.ok(g.player.vy<-500);g.keys.jump=false;step(g,1/60);assert.ok(g.player.vy>-250);});
